# Generated by Django 5.0.6 on 2024-09-11 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mozzify', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='product_imgs/')),
                ('slug', models.CharField(max_length=400)),
                ('detail', models.TextField()),
                ('specs', models.TextField()),
                ('price', models.PositiveBigIntegerField()),
                ('status', models.BooleanField(default=True)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mozzify.category')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mozzify.brand')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mozzify.color')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mozzify.size')),
            ],
        ),
    ]
