# Generated by Django 5.0.6 on 2024-09-13 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mozzify', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=200)),
                ('alt_text', models.CharField(max_length=320)),
            ],
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mozzify.color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mozzify.product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mozzify.size')),
            ],
        ),
    ]
